eye = input("Please enter a character for the eye")

print(" _ ########## _")
print(f"| |# {eye}    {eye} #| |")
print("|_|#        #|_|")
print("   ##########   ")
print("    / /   \ \    ")
print("   ( / --- \ )    ")
print("    / o     \      ")
print("   (         )     ")
print("    (_______)      ")
print("                  ")