heart_nb = int(input("Please enter the nmber of lives "))
heart = heart_nb*chr(3)
print('\n')
energy_nb= int(input("Please enter the energy level "))
energy = energy_nb*chr(4)
print('\n')
shield_nb = int(input("Please enter the shield level "))
shield = shield_nb*chr(4)
print("\n")
print("Health has been set.")
print("\n")
print(f"Lives: {heart}")
print(f"Energy: {energy}")
print(f"Shield: {shield}")