print(" _ ########## _")
print("| |# __  __ #| |")
print("|_|#        #|_|")
print("   ##########   ")
print("    / /   \ \    ")
print("   ( / --- \ )    ")
print("    / o     \      ")
print("   (         )     ")
print("    (_______)      ")
print("                  ")