print("System Failure Imminent!\nSystem rebooy has been initiated...")
print()
print("...rebooying sensory system")
print("...rebooying output motors")
print("...rebooying hover engine")
print()
print("System online.")
